export type AmazonCategoryNode = {
  category: string;
  subcategories: string[];
};

// Amazon-facing product taxonomy seed used for OMS SKU enrichment. SP-API
// Product Type Definitions still validates exact listing requirements before
// publishing; this tree gives operators a fast account-level catalog picker.
export const AMAZON_CATEGORY_TREE: AmazonCategoryNode[] = [
  { category: 'Amazon Devices & Accessories', subcategories: ['Echo & Alexa Devices', 'Fire Tablets', 'Fire TV', 'Kindle E-readers', 'Smart Home Devices', 'Device Accessories'] },
  { category: 'Appliances', subcategories: ['Cooktops', 'Dishwashers', 'Freezers', 'Laundry Appliances', 'Microwaves', 'Range Hoods', 'Ranges', 'Refrigerators', 'Small Appliances', 'Wine Cellars'] },
  { category: 'Arts, Crafts & Sewing', subcategories: ['Art Supplies', 'Beading & Jewelry Making', 'Craft Supplies', 'Fabric', 'Knitting & Crochet', 'Needlework', 'Organization & Storage', 'Painting', 'Scrapbooking', 'Sewing'] },
  { category: 'Automotive', subcategories: ['Car Care', 'Car Electronics', 'Exterior Accessories', 'Interior Accessories', 'Motorcycle & Powersports', 'Oils & Fluids', 'Paint & Body', 'Parts', 'Performance Parts', 'Replacement Parts', 'RV Parts & Accessories', 'Tools & Equipment', 'Tires & Wheels'] },
  { category: 'Baby', subcategories: ['Activity & Entertainment', 'Baby Care', 'Baby Gear', 'Baby Stationery', 'Car Seats', 'Diapering', 'Feeding', 'Gifts', 'Nursery', 'Potty Training', 'Pregnancy & Maternity', 'Safety', 'Strollers'] },
  { category: 'Beauty & Personal Care', subcategories: ['Bath & Body', 'Beauty Tools', 'Fragrance', 'Hair Care', 'Makeup', 'Nail Care', 'Oral Care', 'Personal Care', 'Salon & Spa', 'Shaving & Hair Removal', 'Skin Care'] },
  { category: 'Books', subcategories: ['Arts & Photography', 'Biographies & Memoirs', 'Business & Money', 'Calendars', 'Children Books', 'Comics & Graphic Novels', 'Computers & Technology', 'Cookbooks', 'Education & Teaching', 'Health Fitness & Dieting', 'Literature & Fiction', 'Mystery Thriller & Suspense', 'Reference', 'Religion & Spirituality', 'Romance', 'Science Fiction & Fantasy', 'Self Help', 'Teen & Young Adult'] },
  { category: 'Camera & Photo', subcategories: ['Accessories', 'Binoculars & Scopes', 'Camera Bags', 'Digital Cameras', 'Film Photography', 'Flashes', 'Lenses', 'Lighting & Studio', 'Printers & Scanners', 'Surveillance Cameras', 'Tripods & Monopods', 'Video'] },
  { category: 'Cell Phones & Accessories', subcategories: ['Accessories', 'Bluetooth Headsets', 'Cases Holsters & Sleeves', 'Chargers & Power Adapters', 'Cell Phones', 'Mobile Broadband', 'Prepaid Phones', 'Screen Protectors', 'SIM Cards', 'Smart Watches'] },
  { category: 'Clothing, Shoes & Jewelry', subcategories: ['Baby Clothing', 'Boys Clothing', 'Costumes', 'Girls Clothing', 'Handbags', 'Jewelry', 'Luggage', 'Men Clothing', 'Men Shoes', 'Novelty & More', 'Shoe Accessories', 'Uniforms Work & Safety', 'Watches', 'Women Clothing', 'Women Shoes'] },
  { category: 'Collectibles & Fine Art', subcategories: ['Antiques', 'Coins', 'Entertainment Collectibles', 'Fine Art', 'Sports Collectibles', 'Trading Cards'] },
  { category: 'Computers & Accessories', subcategories: ['Computer Accessories', 'Computer Components', 'Data Storage', 'Desktops', 'External Components', 'Laptop Accessories', 'Laptops', 'Monitors', 'Networking Products', 'Printers', 'Scanners', 'Servers', 'Tablets', 'Tablet Accessories'] },
  { category: 'Electronics', subcategories: ['Accessories & Supplies', 'Audio & Video Accessories', 'Car & Vehicle Electronics', 'Computers & Accessories', 'GPS & Navigation', 'Headphones', 'Home Audio', 'Office Electronics', 'Portable Audio & Video', 'Security & Surveillance', 'Television & Video', 'Wearable Technology'] },
  { category: 'Grocery & Gourmet Food', subcategories: ['Alcoholic Beverages', 'Baby Foods', 'Beverages', 'Breakfast Foods', 'Candy & Chocolate', 'Canned Jarred & Packaged Foods', 'Cooking & Baking', 'Dairy Cheese & Eggs', 'Deli & Prepared Foods', 'Fresh Flowers & Live Indoor Plants', 'Fresh Meal Kits', 'Fresh Produce', 'Frozen', 'Herbs Spices & Seasonings', 'Meat & Seafood', 'Pantry Staples', 'Snack Foods'] },
  { category: 'Handmade', subcategories: ['Artwork', 'Baby', 'Beauty & Grooming', 'Clothing Shoes & Accessories', 'Home & Kitchen', 'Jewelry', 'Pet Supplies', 'Stationery & Party Supplies', 'Toys & Games'] },
  { category: 'Health & Household', subcategories: ['Baby & Child Care', 'Health Care', 'Household Supplies', 'Medical Supplies & Equipment', 'Nutrition', 'Personal Care', 'Sexual Wellness', 'Sports Nutrition', 'Stationery & Gift Wrapping', 'Vision Care', 'Wellness & Relaxation'] },
  { category: 'Home & Kitchen', subcategories: ['Bath', 'Bedding', 'Cleaning Supplies', 'Event & Party Supplies', 'Furniture', 'Heating Cooling & Air Quality', 'Home Decor', 'Irons & Steamers', 'Kids Home Store', 'Kitchen & Dining', 'Seasonal Decor', 'Storage & Organization', 'Vacuums & Floor Care', 'Wall Art', 'Window Treatments'] },
  { category: 'Industrial & Scientific', subcategories: ['Abrasive & Finishing Products', 'Additive Manufacturing Products', 'Commercial Door Products', 'Cutting Tools', 'Fasteners', 'Filtration', 'Food Service Equipment & Supplies', 'Hydraulics Pneumatics & Plumbing', 'Industrial Electrical', 'Janitorial & Sanitation Supplies', 'Lab & Scientific Products', 'Material Handling Products', 'Occupational Health & Safety', 'Packaging & Shipping Supplies', 'Power & Hand Tools', 'Professional Dental Supplies', 'Raw Materials', 'Retail Store Fixtures & Equipment', 'Test Measure & Inspect'] },
  { category: 'Kitchen & Dining', subcategories: ['Bakeware', 'Coffee Tea & Espresso', 'Cookware', 'Dining & Entertaining', 'Home Brewing & Wine Making', 'Kitchen Knives & Cutlery Accessories', 'Kitchen Storage & Organization', 'Kitchen Utensils & Gadgets', 'Small Appliance Parts & Accessories', 'Small Appliances', 'Tabletop'] },
  { category: 'Musical Instruments', subcategories: ['Amplifiers & Effects', 'Band & Orchestra', 'Bass Guitars', 'DJ Electronic Music & Karaoke', 'Drums & Percussion', 'Guitars', 'Instrument Accessories', 'Keyboards & MIDI', 'Live Sound & Stage', 'Microphones', 'Recording Equipment'] },
  { category: 'Office Products', subcategories: ['Calendars Planners & Personal Organizers', 'Education & Crafts', 'Office Electronics', 'Office Furniture & Lighting', 'Office Supplies', 'Paper', 'Pens Pencils & Writing Supplies', 'Presentation Supplies', 'Printer Ink & Toner', 'School Supplies'] },
  { category: 'Patio, Lawn & Garden', subcategories: ['Farm & Ranch', 'Gardening & Lawn Care', 'Generators & Portable Power', 'Grills & Outdoor Cooking', 'Outdoor Decor', 'Outdoor Heating & Cooling', 'Outdoor Power Tools', 'Patio Furniture & Accessories', 'Pest Control', 'Pools Hot Tubs & Supplies', 'Snow Removal'] },
  { category: 'Pet Supplies', subcategories: ['Birds', 'Cats', 'Dogs', 'Fish & Aquatic Pets', 'Horses', 'Reptiles & Amphibians', 'Small Animals'] },
  { category: 'Software', subcategories: ['Accounting & Finance', 'Antivirus & Security', 'Business & Office', 'Children Software', 'Design & Illustration', 'Digital Software', 'Education & Reference', 'Games', 'Lifestyle & Hobbies', 'Music', 'Networking & Servers', 'Operating Systems', 'Photography', 'Programming & Web Development', 'Tax Preparation', 'Utilities'] },
  { category: 'Sports & Outdoors', subcategories: ['Airsoft & Paintball', 'Boating & Sailing', 'Camping & Hiking', 'Climbing', 'Cycling', 'Exercise & Fitness', 'Fan Shop', 'Fishing', 'Golf', 'Hunting & Fishing', 'Leisure Sports & Game Room', 'Outdoor Recreation', 'Running', 'Skates Skateboards & Scooters', 'Sports & Fitness', 'Team Sports', 'Water Sports', 'Winter Sports'] },
  { category: 'Tools & Home Improvement', subcategories: ['Appliances', 'Building Supplies', 'Electrical', 'Hardware', 'Kitchen & Bath Fixtures', 'Light Bulbs', 'Lighting & Ceiling Fans', 'Measuring & Layout Tools', 'Paint Wall Treatments & Supplies', 'Power & Hand Tools', 'Rough Plumbing', 'Safety & Security', 'Storage & Home Organization', 'Welding & Soldering'] },
  { category: 'Toys & Games', subcategories: ['Action Figures & Statues', 'Arts & Crafts', 'Baby & Toddler Toys', 'Building Toys', 'Dolls & Accessories', 'Dress Up & Pretend Play', 'Electronics for Kids', 'Games & Accessories', 'Grown-Up Toys', 'Hobbies', 'Kids Furniture Decor & Storage', 'Learning & Education', 'Novelty & Gag Toys', 'Party Supplies', 'Puzzles', 'Sports & Outdoor Play', 'Stuffed Animals & Plush Toys', 'Toy Remote Control & Play Vehicles', 'Tricycles Scooters & Wagons'] },
  { category: 'Video Games', subcategories: ['Accessories', 'Digital Games', 'Legacy Systems', 'Mac Games', 'Nintendo Switch', 'PC Games', 'PlayStation 4', 'PlayStation 5', 'Virtual Reality', 'Xbox One', 'Xbox Series X & S'] },
];

export const amazonCategoryNames = AMAZON_CATEGORY_TREE.map((node) => node.category);

export function amazonSubcategoriesFor(category: string) {
  const selected = AMAZON_CATEGORY_TREE.find((node) => node.category.toLowerCase() === category.trim().toLowerCase());
  return selected?.subcategories || [];
}
