export type CatalogItem = {
  _id: string;
  sku: string;
  title: string;
  description?: string;
  image?: string;
  images?: string[];
  upc?: string;
  ean?: string;
  asin?: string;
  category?: string;
  subCategory?: string;
  enrichmentState?: string;
  enrichmentMarker?: string;
  keepaUnavailable?: boolean;
  lob?: string;
  weight?: number;
  dimensions?: { length: number; width: number; height: number };
  tags?: string[];
  supplierId?: string;
  channels?: string[];
  mappings?: { channel: string; channelDisplay?: string }[];
  wmsInventory?: {
    inbound: number;
    received: number;
    available: number;
    orders: number;
    shippedToday: number;
    openAsnsCount?: number;
    receiving?: number;
  };
  createdAt?: string;
  updatedAt?: string;
};
